# -*- coding: utf-8 -*-
"""area calculation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1drJzwaic5yyfFdV-BeYOMF1VXYZ5DKPs
"""

area = 0
def square_area(s):
  area=s**2
  return area
def rectangle_area(w,l):
  area=w*l
  return area
def circle_area(r):
  area=3.14 * r**2
  return area
shape=input("enter shape (square-rectangle-circle) : ")

if shape=="square":
  side=int(input("enter side of square : "))
  print("square area = ",square_area(side))
elif shape=="rectangle":
  width=int(input("enter width : "))
  length=int(input("enter length : "))
  print("rectangle area = ",rectangle_area(width,length))
elif shape=="circle":
  radius=int(input("enter radius : "))
  print("circle area = ",circle_area(radius))
else:
  print("error")